# git aliases
alias gp="git push"
alias gpf="git push --force-with-lease"
alias gpl="git pull"
alias gr="git rebase"
alias gc="git add . && cz"
alias grm="gr origin/main"
alias gco="git checkout"
alias gcr="gc && grm"
alias grp="grm && gpf"
alias gcrp="gc && grp"
alias gca="git add . && git commit --amend --no-edit"
alias gcarp="gca && grp"
alias gcom="gco main && grp"
alias gb="git branch"
alias gsta="git add . && git stash"
alias gstap="git stash pop"
